# Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, whenincreasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.



In [ ]:
import numpy

def matrix_formation(x,N,increasing=False):
    x = numpy.array(x)
    if (increasing):
        return numpy.column_stack([x**(i) for i in range(N)]) 
    else:
        return numpy.column_stack([x**(N-1-i) for i in range(N)])  

In [11]:
input_array=[1,2,3,5]
columns = 5
increasing =False


output = matrix_formation(input_array,columns,increasing)
print("The output array:-\n",output)

The output array:-
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]


# Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:
def mov_avg(mylist, N):
    mylist, moving_av = [0], []
    for i, x in enumerate(mylist, 1):
        mylist.append(mylist[i-1] + x) 
        if i>=N:
            temp = round(((mylist[i] - mylist[i-N])/N),2) #computing the moving average using temp array sum array cumsum
            #can do stuff with moving_ave here
            moving_av.append(temp) 
    print("Moving average values list: ", moving_av)
    print("Length of the list l-N+1: ", len(moving_av))

In [ ]:
mylist = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
N = 4

mov_avg(mylist,N)